### ISSUE TITLE
cannot import name 'video_metadata' from 'ethon.pyfunc'

### ISSUE THREAD

**Issue by catbonny** [gagharutyunyan1993/SaveRestrictedContentBot#1]
2023-03-09 21:13:46 srcbot  | starting Bot ~@DroneBots
2023-03-09 21:13:57 srcbot  | Traceback (most recent call last):
2023-03-09 21:13:57 srcbot  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-03-09 21:13:57 srcbot  |     return _run_code(code, main_globals, None,
2023-03-09 21:13:57 srcbot  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-03-09 21:13:57 srcbot  |     exec(code, run_globals)
2023-03-09 21:13:57 srcbot  |   File "/app/main/__main__.py", line 16, in <module>
2023-03-09 21:13:57 srcbot  |     load_plugins(plugin_name.replace(".py", ""))
2023-03-09 21:13:57 srcbot  |   File "/app/main/utils.py", line 12, in load_plugins
2023-03-09 21:13:57 srcbot  |     spec.loader.exec_module(load)
2023-03-09 21:13:57 srcbot  |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
2023-03-09 21:13:57 srcbot  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-03-09 21:13:57 srcbot  |   File "main/plugins/frontend.py", line 8, in <module>
2023-03-09 21:13:57 srcbot  |     from main.plugins.pyroplug import get_msg
2023-03-09 21:13:57 srcbot  |   File "/app/main/plugins/pyroplug.py", line 11, in <module>
2023-03-09 21:13:57 srcbot  |     from ethon.pyfunc import video_metadata
2023-03-09 21:13:57 srcbot  | ImportError: cannot import name 'video_metadata' from 'ethon.pyfunc' (/usr/local/lib/python3.9/site-packages/ethon/pyfunc.py)
2023-03-09 21:13:57 srcbot  | main has Imported helpers
2023-03-09 21:13:57 srcbot  | main has Imported start
1970-01-01 00:00:00 srcbot exited with code 1
1970-01-01 00:00:00

**Comment by gagharutyunyan1993** [comment]
> 2023-03-09 21:13:46 srcbot | starting Bot ~@DroneBots 2023-03-09 21:13:57 srcbot | Traceback (most recent call last): 2023-03-09 21:13:57 srcbot | File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main 2023-03-09 21:13:57 srcbot | return _run_code(code, main_globals, None, 2023-03-09 21:13:57 srcbot | File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code 2023-03-09 21:13:57 srcbot | exec(code, run_globals) 2023-03-09 21:13:57 srcbot | File "/app/main/**main**.py", line 16, in 2023-03-09 21:13:57 srcbot | load_plugins(plugin_name.replace(".py", "")) 2023-03-09 21:13:57 srcbot | File "/app/main/utils.py", line 12, in load_plugins 2023-03-09 21:13:57 srcbot | spec.loader.exec_module(load) 2023-03-09 21:13:57 srcbot | File "", line 790, in exec_module 2023-03-09 21:13:57 srcbot | File "", line 228, in _call_with_frames_removed 2023-03-09 21:13:57 srcbot | File "main/plugins/frontend.py", line 8, in 2023-03-09 21:13:57 srcbot | from main.plugins.pyroplug import get_msg 2023-03-09 21:13:57 srcbot | File "/app/main/plugins/pyroplug.py", line 11, in 2023-03-09 21:13:57 srcbot | from ethon.pyfunc import video_metadata 2023-03-09 21:13:57 srcbot | ImportError: cannot import name 'video_metadata' from 'ethon.pyfunc' (/usr/local/lib/python3.9/site-packages/ethon/pyfunc.py) 2023-03-09 21:13:57 srcbot | main has Imported helpers 2023-03-09 21:13:57 srcbot | main has Imported start 1970-01-01 00:00:00 srcbot exited with code 1 1970-01-01 00:00:00

Please, show what you have in the equirements.txt file.

**Comment by gagharutyunyan1993** [comment]
Try to fork and use this repo.
